version: '3.8'

services:
  frontend:
    build:
      context: ./youtube_summerizer
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    volumes:
      - ./youtube_summerizer:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - REACT_APP_AUTH_URL=http://localhost:8000
    networks:
      - app-network
    depends_on:
      - backend
      - auth

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    networks:
      - app-network

  auth:
    build:
      context: ./youtube_history
      dockerfile: DockerFile
    volumes:
      - ./youtube_history:/app
    ports:
      - "8000:8000"
    env_file:
      - youtube_history/youtube_history/.env
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network
    depends_on:
      - dbauth

  dbauth:
    platform: linux/amd64
    container_name: dbauth
    image: postgres:15
    environment:
      - POSTGRES_DB=yt_summerizer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vaibhavi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: